In [ ]:
import pandas as pd
import set_paths
from src.utils import get_files
from src.preprocessing import load_citas_df
from src.kpis import leads_tot_vs_regis, citas_vs_regis
from config.paths import *

In [2]:
crm_df = pd.read_csv(CRM / get_files(CRM)[0])
citas = load_citas_df(CITAS / get_files(CITAS)[0])
test = leads_tot_vs_regis(crm_df= crm_df)
test

             conteo  pct_tot
Interesados     345     1.00
Registrados     231     0.67

In [4]:
test = citas_vs_regis(citas = citas,
                      decimals = 3)
test.head()

             conteo    pct
total          21.0  100.0
registradas    21.0  100.0