In [1]:
import pandas as pd

import set_paths
from config.paths import *
from config.config import columnas_archivo_citas
from src.utils import get_files, strip_df
from src.preprocessing import load_citas_df
from src.kpis import desglose_citas_asesor, leads_totales_asesor, ventas_asesor

In [2]:
periodo = 0
crm_path = get_files(CRM)
crm_df = pd.read_csv(CRM/ crm_path[0])
citas = load_citas_df(CITAS / get_files(CITAS)[0])

In [3]:
total_leads = leads_totales_asesor(crm_df)
total_leads

                                 asesor  total_leads
0       Diana Elizabeth Vivanco Galindo           79
1          Jimena Denisse Hansen Garcia           67
2                      Leonardo Furlong           39
3        Valentina Mariel Salgado Arias           36
4         Victor Manuel Garcia Bautista           35
5                       Jose Luis Nuñez           29
6                 Daniel Guerra Almazan           28
7               Alejandra Aurora Corona           27
8       Patricia Nathalie Mijares Perez           27
9         Jose Manuel Alvarez Hernandez           18
10              Ana Laura Flores Garcia           14
11       Dubia Elizabeth Ilescas Gudiño           13
12                    Jaqueline Jiménez           13
13  Betsy Eliett Vanessa Herrera Rivera           11
14      Claudia Angelica Del toro Perez           10
15            Manuel Omar Moreno Zapata            9
16                Yolanda Rojas Aguilar            6
17             Ana Janeth Reyes Jimenes            4
18                   Esteban Quito Rojo            3
19               Aldo Granados Granados            2
20                         Daniel Rojas            2
21             Alejandro Artola Alvarez            1

In [4]:
total_citas = desglose_citas_asesor(citas_df= citas)
total_citas

                   atendida  reagendada  cancelada  otros  total
Valentina Salgado         2           4          1      0      7
Daniel Guerra             3           1          1      0      5
Patricia Mijares          0           1          2      0      3
Yolanda Rojas             0           0          1      0      1
Omar  Moreno              2           0          0      0      2
Diana Vivanco             0           2          1      0      3

In [5]:
test_ventas = ventas_asesor(citas_df = citas)
test_ventas

              ASESOR  VENTAS
0      Daniel Guerra     0.0
1      Diana Vivanco     0.0
2       Omar  Moreno     0.0
3   Patricia Mijares     0.0
4  Valentina Salgado     1.0
5      Yolanda Rojas     0.0