In [1]:
import pandas as pd
import set_paths
from src.utils import get_files
from src.preprocessing import load_citas_df
from src.kpis import leads_tot_vs_regis, citas_vs_regis, full_sales_funnel_pipeline, flujo_de_leads
from config.paths import *

In [2]:
crm_df = pd.read_csv(CRM / get_files(CRM)[2])
citas_df = load_citas_df(CITAS / get_files(CITAS)[0])
test = leads_tot_vs_regis(crm_df= crm_df)
test

             conteo  pct_tot
Interesados     345    1.000
Registrados       1    0.003

In [3]:
test = citas_vs_regis(citas = citas_df,
                      decimals = 3)
test.head()

             conteo    pct
total          21.0  100.0
registradas    21.0  100.0

In [4]:
embudo_ventas = full_sales_funnel_pipeline(estad_portales=ESTAD_PORTALES,
                                           inter_portales=INTERESADOS,
                                           crm_df=crm_df,
                                           citas_df=citas_df,
                                           pct_decimals = 3)

embudo_ventas

                     conteo  pct_tot  pct_rel
Exposición         226173.0    1.000    1.000
Visualizaciones      8656.0    0.038    0.038
Interesados           203.0    0.001    0.023
Registrados             1.0    0.000    0.005
Traspasados             1.0    0.000    1.000
Citas                  21.0    0.000   21.000
Citas registradas      21.0    0.000    1.000
Ventas                  1.0    0.000    0.048

In [5]:
inicio_periodo = "21/08/2026"
fin_periodo = "27/08/2026"
flujo_de_leads(crm_df = crm_df,
               inicio_periodo = inicio_periodo,
               fin_periodo = fin_periodo)

               conteo    pct
totales           394  1.000
nuevos              0  0.000
seguimiento       211  0.536
estancados        211  0.536
fin_sin_venta     111  0.282