In [1]:
import pandas as pd
import set_paths
from src.utils import get_files
from src.preprocessing import load_citas_df
from src.kpis import leads_tot_vs_regis, citas_vs_regis
from config.paths import *

In [2]:
crm_df = pd.read_csv(CRM / get_files(CRM)[0])
citas = load_citas_df(CITAS / get_files(CITAS)[0])
test = leads_tot_vs_regis(crm_df= crm_df)
test

             conteo  pct_tot
Interesados     345     1.00
Registrados     231     0.67

In [3]:
test = citas_vs_regis(citas = citas,
                      decimals = 3)
test.head()

             conteo    pct
total          21.0  100.0
registradas    21.0  100.0

In [4]:
import pandas as pd

from config.paths import CITAS, CRM, ESTAD_PORTALES, INTERESADOS
from src.preprocessing import load_citas_df
from src.utils import get_files
from src.kpis import full_sales_funnel_pipeline

crm_df = pd.read_csv(CRM / get_files(CRM)[0])
citas_df = load_citas_df(CITAS / get_files(CITAS)[0])

embudo_ventas = full_sales_funnel_pipeline(
    estad_portales=ESTAD_PORTALES,
    inter_portales=INTERESADOS,
    crm_df=crm_df,
    citas_df=citas_df,
)

embudo_ventas

                     conteo  pct_tot  pct_rel
Exposición         226173.0    1.000    1.000
Visualizaciones      8656.0    0.038    0.038
Interesados           203.0    0.001    0.023
Registrados           199.0    0.001    0.980
Traspasados           199.0    0.001    1.000
Citas                  21.0    0.000    0.106
Citas registradas      21.0    0.000    1.000
Ventas                  1.0    0.000    0.048