In [1]:
import pandas as pd

import set_paths
from config.paths import *
#from config.config import columnas_archivo_citas
from src.utils import get_files#,# strip_df
from src.preprocessing import load_citas_df
from src.kpis import desglose_citas_asesor, leads_totales_asesor, ventas_asesor

In [2]:
periodo = 0
crm_path = get_files(CRM)
crm_df = pd.read_csv(CRM/ crm_path[2])
citas = load_citas_df(CITAS / get_files(CITAS)[0])

In [3]:
total_leads = leads_totales_asesor(crm_df)
total_leads

                                 asesor  total_leads
0                      Leonardo Furlong          132
1       Diana Elizabeth Vivanco Galindo           42
2               Alejandra Aurora Corona           41
3         Jose Manuel Alvarez Hernandez           29
4         Victor Manuel Garcia Bautista           29
5                     Jaqueline Jiménez           26
6                 Daniel Guerra Almazan           21
7                 Yolanda Rojas Aguilar           20
8        Valentina Mariel Salgado Arias           16
9       Patricia Nathalie Mijares Perez           13
10            Manuel Omar Moreno Zapata            8
11             Alejandro Artola Alvarez            5
12             Ana Janeth Reyes Jimenes            5
13      Claudia Angelica Del toro Perez            2
14                      Jose Luis Nuñez            2
15            Johana Vanessa Arias Lara            1
16              Ana Laura Flores Garcia            1
17  Betsy Eliett Vanessa Herrera Rivera            1

In [4]:
total_citas = desglose_citas_asesor(citas_df= citas)
total_citas

                   atendida  reagendada  cancelada  otros  total
Valentina Salgado         2           4          1      0      7
Daniel Guerra             3           1          1      0      5
Patricia Mijares          0           1          2      0      3
Yolanda Rojas             0           0          1      0      1
Omar  Moreno              2           0          0      0      2
Diana Vivanco             0           2          1      0      3

In [5]:
test_ventas = ventas_asesor(citas_df = citas)
test_ventas

              ASESOR  VENTAS
0      Daniel Guerra     0.0
1      Diana Vivanco     0.0
2       Omar  Moreno     0.0
3   Patricia Mijares     0.0
4  Valentina Salgado     1.0
5      Yolanda Rojas     0.0