In [1]:
import pandas as pd
import set_paths
from src.utils import get_files
from src.preprocessing import load_citas_df
from src.kpis import leads_tot_vs_regis, citas_vs_regis, full_sales_funnel_pipeline, flujo_de_leads
from config.paths import *

In [3]:
crm_df = pd.read_csv(CRM / get_files(CRM)[0])
citas_df = load_citas_df(CITAS / get_files(CITAS)[0])
test = leads_tot_vs_regis(crm_df= crm_df)
test

             conteo  pct_tot
Interesados     413    1.000
Registrados     241    0.584

In [4]:
test = citas_vs_regis(citas = citas_df,
                      decimals = 3)
test.head()

             conteo    pct
total          20.0  100.0
registradas    20.0  100.0

In [8]:
embudo_ventas = full_sales_funnel_pipeline(estad_portales=ESTAD_PORTALES,
                                           inter_portales=INTERESADOS,
                                           crm_df=crm_df,
                                           citas_df=citas_df,
                                           pct_decimals = 3,
                                           start = 1)

embudo_ventas

                     conteo  pct_tot  pct_rel
Exposición         397265.0    1.000    1.000
Visualizaciones     17836.0    0.045    0.045
Interesados           413.0    0.001    0.023
Registrados           241.0    0.001    0.584
Traspasados           228.0    0.001    0.946
Citas                  20.0    0.000    0.088
Citas registradas      20.0    0.000    1.000
Ventas                  1.0    0.000    0.050

In [11]:
inicio_periodo = "04/09/2026"
fin_periodo = "10/09/2026"
flujo_de_leads(crm_df = crm_df,
               inicio_periodo = inicio_periodo,
               fin_periodo = fin_periodo)

               conteo    pct
totales           408  1.000
nuevos            343  0.841
seguimiento       243  0.596
estancados         31  0.076
fin_sin_venta      83  0.203