In [1]:
import pandas as pd
import set_paths
from config.paths import SCHEMAS, DATA, CRM, CITAS, INTERESADOS, ESTAD_PORTALES
from src.clean_tables import load_table
from src.utils import get_files
import yaml

In [2]:
table_path = get_files(CRM)[0]
test = load_table(path = CRM/table_path,
           yaml_path = SCHEMAS/"leads_table.YAML")
test

,id_lead,nombre,apellido,email,telefono,portal_origen,tipo,operacion,precio,estado,...,fecha_ultima_actividad,ultimo_asesor_activo,abierto,hubo_venta_pago,solo_firmado,monto_venta,fecha_cierre,fecha_cierre_venta,dias_activo,id_aviso
0,5735,Gladys Estrada,Alejo,gladysestrada1085@hotmail.com,525547079333,Inmuebles24,departamento,comprar,1236498,Ciudad de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
1,5734,naymarin,N,naymarin81@gmail.com,525617758225,Inmuebles24,departamento,comprar,986263,Ciudad de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
2,5733,naymarin,N,naymarin81@gmail.com,525617758225,Inmuebles24,casa,comprar,850000,Estado de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
3,5732,Elvia,N,elvia.ab76@gmail.com,525566031276,Inmuebles24,departamento,comprar,970000,Estado de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
4,5731,Monica,N,moan31@yahoo.com.mx,525534767305,Inmuebles24,departamento,comprar,1738188,Ciudad de México,...,2026-06-19 11:03:00,Luis Néstor Portilla Vázquez,True,False,False,0,NaT,NaT,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4847,9759,Isabel,N,Cyberpalomitas@outlook.com,7471949713,Inmuebles24,departamento,comprar,1140000,Ciudad de México,...,NaT,Victor Manuel Garcia Bautista,False,False,False,0,NaT,NaT,6,147135173
4848,9758,Isabel,N,Cyberpalomitas@outlook.com,7471949713,Inmuebles24,departamento,comprar,1140000,Ciudad de México,...,NaT,Victor Manuel Garcia Bautista,False,False,False,0,NaT,NaT,6,0
4849,9756,Daniel,Cuautle,<NA>,5574261711,Cartera,duplex,comprar,510000,edomx,...,NaT,Diana Elizabeth Vivanco Galindo,True,False,False,0,NaT,NaT,10,0
4850,9755,Mayela,<NA>,zarazua.mayela9@gmail.com,5534285712,Inmuebles24,departamento,comprar,1569100,edomx,...,NaT,Diana Elizabeth Vivanco Galindo,False,False,False,0,NaT,NaT,0,150794290
4851,9754,Granados,Granados,aguilar.bienes33@gmail.com,5641235367,Inmuebles24,departamento,comprar,2165000,CDMX,...,NaT,Diana Elizabeth Vivanco Galindo,False,False,False,0,NaT,NaT,0,150778390

In [3]:
5076 in test["id_lead"].values

False

In [4]:
citas_test_path = get_files(CITAS)[1]
citas_test = load_table(path=CITAS / citas_test_path,
                        yaml_path= SCHEMAS/"historico_citas.YAML")
citas_test

,id_cita,id_lead,fecha_solicitud,fecha_cita,cliente,asesor,gerente,asistencia,n_cita,producto,tipo_cita,captacion,registrado_crm,ventas
64,65,7483,2026-07-23,2026-07-25,Fabiola Gonzalez,Daniel Guerra,Leonardo Furlong,atendida,1,Residencial,Inmueble,Inmuebles 24,False,0
66,67,7802,2026-07-24,2026-07-27,Alberto Romero,Omar Moreno,Daniel Rojas,cancelada,1,outlet,presencial,Cartera Propia,True,0
67,68,7224,2026-07-27,2026-07-27,Maria del Rosario,Diana Vivanco,Daniel Rojas,atendida,1,outlet,videollamada,Inmuebles 24,True,0
69,70,5547,2026-07-21,2026-07-28,Angel Rios,Patricia Mijares,Daniel Rojas,atendida,2,Tickets,videollamada,Cartera Propia,True,0
70,71,7222,2026-07-28,2026-07-28,Maria Lilia Vergara,Diana Vivanco,Daniel Rojas,atendida,1,outlet,videollamada,Inmuebles 24,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,158,9620,2026-02-09,2026-03-09,Maria Patricia Flores,Ana Flores,Alejandro Artola,cancelada,1,Outlet,inmueble,Inmuebles24,True,0
158,159,9965,2026-02-09,2026-03-09,Mariana Orozco,Diana Vivanco,Omar Moreno,cancelada,1,Outlet,Presencial,Cartera,True,0
159,160,9853,2026-01-09,2026-03-09,Gerardo Barranco,Diana Vivanco,Omar Moreno,cancelada,1,Outlet,Presencial,Inmuebles24,True,0
160,161,9969,2026-02-09,2026-03-09,Gerardo Barranco,Janeth Reyes,Jaime Morales,cancelada,1,Outlet,Presencial,cartera,True,0
161,162,9259,2026-01-09,2026-03-09,Katia Robles,Yolanda Rojas,Leonardo Furlong,reagendada,1,Residencial,Presencial,Redes Sociales,True,0

In [5]:
inter_test_path = get_files(INTERESADOS)[1]
inter_test = load_table(path=INTERESADOS / inter_test_path,
                        yaml_path= SCHEMAS/"interesados_table.YAML")
inter_test

,nombre_apellido,email,telefono,telefono_2,id_portal,fecha,id_aviso,codigo,provincia,ciudad,barrio,tipo_propiedad,tipo_operacion,precio
0,Raul,raulgoh7@gmail.com,5530808634,<NA>,1,2026-09-09 17:40:00,150965844,BH81,Ciudad de México,Benito Juárez,Actipan,Departamento,Venta,2100000
1,DIEGO,d.becies@altaltiumrealestates.com,525621881886,5621881886,1,2026-09-09 17:36:00,151043903,DB80,Ciudad de México,Alvaro Obregón,Jardines del Pedregal,Casa,Venta,9850000
2,Norma Rebeca Fernández cantero Norma Fernández,norma.fernandez51@yahoo.com.mx,525632716621,<NA>,1,2026-09-09 17:16:00,150807882,JN79,Ciudad de México,Venustiano Carranza,Jardín Balbuena,Casa,Venta,2700000
3,Diana,darzt@jowat.com,525647075275,525647075275,1,2026-09-09 17:05:00,150910972,DB80,Ciudad de México,Benito Juárez,Insurgentes Mixcoac,Departamento,Venta,1900000
4,Karen,gytabogados@hotmail.com,5538965293,5538965293,1,2026-09-09 16:19:00,150981070,JA48,Ciudad de México,Venustiano Carranza,Moctezuma,Departamento,Venta,1192542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4362,Elizabeth,elyz411cg@gmail.com,525584764514,525584764514,4,2026-06-12 17:00:00,149831218,DIr1,Edo. de México,Cuautitlán Izcalli,San Francisco Tepojaco,Casa,Venta,1118480
4363,JESSICA,hanna.jv87@gmail.com,525526651677,<NA>,4,2026-06-12 13:37:00,148835238,EL07,Ciudad de México,Cuauhtémoc,Doctores,Departamento,Venta,785000
4364,Karla Gabriela,kgabriela.jacintoc@gmail.com,525529522691,525529522691,4,2026-06-12 08:45:00,149761528,EL07,Ciudad de México,Benito Juárez,Álamos,Departamento,Venta,2092887
4365,Alberto y,aguilaralberto6451@gmail.com,525564966055,525564966055,4,2026-06-12 04:20:00,149306715,EL07,Ciudad de México,Cuauhtémoc,Doctores,Departamento,Venta,785000
4366,Alma Dejesus Ruiz,dejesusruizalma@gmail.com,525561576303,525561576303,4,2026-06-12 02:55:00,149498489,EL07,Edo. de México,Atizapán de Zaragoza,Villas de la Hacienda,Casa,Venta,510000

In [ ]:
from src.db.connect import get_connection
from src.db.insert_table import insert_table
conn = get_connection()
insert_table(
    inter_test,
    SCHEMAS/"interesados_table.YAML",
    conn
)

conn.close()