In [1]:
import pandas as pd
import set_paths
from config.paths import SCHEMAS, DATA, CRM, CITAS, INTERESADOS, ESTAD_PORTALES
from src.clean_tables import load_table
from src.utils import get_files

In [2]:
table_path = get_files(CRM)[0]
test = load_table(path = CRM/table_path,
           yaml_path = SCHEMAS/"leads_table.YAML")
test

,id_lead,nombre,apellido,email,telefono,portal_origen,tipo,operacion,precio,estado,...,fecha_ultima_actividad,ultimo_asesor_activo,abierto,hubo_venta_pago,solo_firmado,monto_venta,fecha_cierre,fecha_cierre_venta,dias_activo,id_aviso
0,5735,Gladys Estrada,Alejo,gladysestrada1085@hotmail.com,525547079333,Inmuebles24,departamento,comprar,1236498,Ciudad de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
1,5734,naymarin,N,naymarin81@gmail.com,525617758225,Inmuebles24,departamento,comprar,986263,Ciudad de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
2,5733,naymarin,N,naymarin81@gmail.com,525617758225,Inmuebles24,casa,comprar,850000,Estado de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
3,5732,Elvia,N,elvia.ab76@gmail.com,525566031276,Inmuebles24,departamento,comprar,970000,Estado de México,...,NaT,<NA>,True,False,False,0,NaT,NaT,0,0
4,5731,Monica,N,moan31@yahoo.com.mx,525534767305,Inmuebles24,departamento,comprar,1738188,Ciudad de México,...,2026-06-19 11:03:00,Luis Néstor Portilla Vázquez,True,False,False,0,NaT,NaT,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4847,9759,Isabel,N,Cyberpalomitas@outlook.com,7471949713,Inmuebles24,departamento,comprar,1140000,Ciudad de México,...,NaT,Victor Manuel Garcia Bautista,False,False,False,0,NaT,NaT,6,147135173
4848,9758,Isabel,N,Cyberpalomitas@outlook.com,7471949713,Inmuebles24,departamento,comprar,1140000,Ciudad de México,...,NaT,Victor Manuel Garcia Bautista,False,False,False,0,NaT,NaT,6,0
4849,9756,Daniel,Cuautle,<NA>,5574261711,Cartera,duplex,comprar,510000,edomx,...,NaT,Diana Elizabeth Vivanco Galindo,True,False,False,0,NaT,NaT,10,0
4850,9755,Mayela,<NA>,zarazua.mayela9@gmail.com,5534285712,Inmuebles24,departamento,comprar,1569100,edomx,...,NaT,Diana Elizabeth Vivanco Galindo,False,False,False,0,NaT,NaT,0,150794290
4851,9754,Granados,Granados,aguilar.bienes33@gmail.com,5641235367,Inmuebles24,departamento,comprar,2165000,CDMX,...,NaT,Diana Elizabeth Vivanco Galindo,False,False,False,0,NaT,NaT,0,150778390

In [3]:
citas_test_path = get_files(CITAS)[0]
citas_test = load_table(path=CITAS / citas_test_path,
                        yaml_path= SCHEMAS/"citas_table.YAML")
citas_test

,id_cita,fecha_solicitud,fecha_cita,cliente,asesor,gerente,asistencia,n_cita,producto,tipo_cita,captacion,registrado_crm,ventas
0,5281,2026-08-19,2026-08-21,Ricardo N,Valentina Salgado,Leonardo Furlong,reagendada,5,outlet,Presencial,Inmuebles 24,True,0
1,9109,2026-08-18,2026-08-21,Adrian Ambrocio,Daniel Guerra,Leonardo Furlong,atendida,1,Residencial,Inmueble,Redes Sociales,True,0
2,9110,2026-08-18,2026-08-21,Jesus Gomez,Daniel Guerra,Leonardo Furlong,cancelada,2,Residencial,Inmueble,Redes Sociales,True,0
3,9304,2026-08-21,2026-08-22,Johana Moran,Patricia Mijares,Victor Garcia,cancelada,1,outlet,Presencial,Marketing,True,0
4,5281,2026-08-20,2026-08-22,Ricardo N,Valentina Salgado,Leonardo Furlong,reagendada,6,outlet,Presencial,Inmuebles 24,True,0
5,8919,2023-08-19,2026-08-23,Erick Iñaqui,Valentina Salgado,Leonardo Furlong,reagendada,1,Residencial,Inmueble,Redes Sociales,True,0
6,9267,2026-08-20,2026-08-23,Angel Perez,Yolanda Rojas,Leonardo Furlong,cancelada,1,Residencial,Inmueble,Redes Sociales,True,0
7,8919,2026-08-19,2026-08-23,Erick Iñaqui,Valentina Salgado,Leonardo Furlong,cancelada,2,Residencial,Inmueble,Redes Sociales,True,0
8,5281,2026-08-20,2026-08-24,Ricardo N,Valentina Salgado,Leonardo Furlong,atendida,7,outlet,Presencial,Inmuebles 24,True,1
9,9376,2026-08-23,2026-08-24,Tania,Daniel Guerra,Leonardo Furlong,atendida,1,Residencial,Inmueble,Redes Sociales,True,0
10,8844,2026-08-18,2026-08-24,Angel N,Patricia Mijares,Victor Garcia,reagendada,1,outlet,Presencial,Inmuebles 24,True,0
11,9478,2026-08-24,2026-08-24,Xareni,Omar Moreno,Jaime Morales,atendida,2,Micro,Presencial,Inmuebles 24,True,0
12,9249,2026-08-24,2026-08-24,Laura santander,Diana Vivanco,Omar Moreno,cancelada,1,outlet,Presencial,Inmuebles 24,True,0
13,9249,2026-08-20,2026-08-24,Laura santander,Diana Vivanco,Omar Moreno,reagendada,2,outlet,Presencial,Inmuebles 24,True,0
14,9028,2026-08-25,2026-08-25,Xareni Corona,Valentina Salgado,Leonardo Furlong,reagendada,1,Residencial,Presencial,Redes Sociales,True,0
15,9478,2026-08-24,2026-08-25,Xareni,Omar Moreno,Jaime Morales,atendida,3,Micro,Presencial,Inmuebles 24,True,0
16,8844,2026-08-24,2026-08-25,Angel N,Patricia Mijares,Victor Garcia,cancelada,2,outlet,Presencial,Inmuebles 24,True,0
17,9109,2026-08-18,2026-08-25,Adrian Ambrocio,Daniel Guerra,Leonardo Furlong,reagendada,2,Residencial,Inmueble,Redes Sociales,True,0
18,9028,2026-08-25,2026-08-25,Xareni Corona,Valentina Salgado,Leonardo Furlong,atendida,2,Residencial,Presencial,Redes Sociales,True,0
19,9377,2026-08-24,2026-08-26,Nayely,Diana Vivanco,Omar Moreno,reagendada,1,outlet,Presencial,Inmuebles 24,True,0
20,9450,2026-08-27,2026-08-27,Christian N,Daniel Guerra,Leonardo Furlong,atendida,1,Residencial,Inmueble,Inmuebles 24,True,0

In [4]:
inter_test_path = get_files(INTERESADOS)[0]
inter_test = load_table(path=INTERESADOS / inter_test_path,
                        yaml_path= SCHEMAS/"interesados_table.YAML")
inter_test

,nombre_apellido,email,telefono,telefono_2,sucursal,mensaje,fecha,id_aviso,codigo,provincia,ciudad,barrio,tipo_propiedad,tipo_operacion,precio,titulo,url_aviso
0,Omar Cardenas Escobar,omarcardenasescobar@gmail.com,525522632696,525522632696,ALTALTIUM REAL ESTATES VENTAS 1,Contactó por Whatsapp,2026-08-27 22:32:00,150834569,Ar68,Ciudad de México,Coyoacán,Copilco Universidad,Departamento,Venta,1575204,VENTA DE DEPARTAMENTO EN AVENIDA UNIVERSIDAD C...,https://www.inmuebles24.com/propiedades/-15083...
1,Erika Ceron,ceronerika097@gmail.com,525559198072,525540162147,ALTALTIUM REAL ESTATES VENTAS 1,Pregunta: ¿Sigue disponible?,2026-08-27 22:18:00,148412855,NA03,Ciudad de México,Xochimilco,Ampliación San Marcos Norte,Departamento,Venta,1120000,"*DEPARTAMENTO EN VENTA* en Ahuejotes, Colonia ...",https://www.inmuebles24.com/propiedades/-14841...
2,AILED ADRIANA PLATA GARCIA,adriana.plata.garcia@gmail.com,7222522654,7222522654,ALTALTIUM REAL ESTATES VENTAS 1,Vió teléfono,2026-08-27 22:10:00,150883227,AR68 01,Ciudad de México,Cuajimalpa de Morelos,Contadero,Departamento,Venta,2150204,DEPARTAMENTO EN VENTA EN CONTADERO EN STAMPA R...,https://www.inmuebles24.com/propiedades/-15088...
3,Rafaela del Rosario Basílio Gutiérrez,basiliogtrz@gmail.com,7441572580,7441572580,ALTALTIUM REAL ESTATES VENTAS 1,Pregunta: En qué etapa está? Se paga directo a...,2026-08-27 22:07:00,150770620,CA72,Ciudad de México,Coyoacán,Paseos de Taxqueña,Casa,Venta,1100000,Casa en Remate en Zona Exclusiva y Tranquila e...,https://www.inmuebles24.com/propiedades/-15077...
4,Betsua Ruiz,betadonay@hotmail.com,5548462589,525548462589,ALTALTIUM REAL ESTATES VENTAS 1,Vió teléfono,2026-08-27 19:53:00,150778338,DV52,Ciudad de México,Benito Juárez,Nápoles,Departamento,Venta,1810000,"Departamento en venta en Arkansas, colonia Náp...",https://www.inmuebles24.com/propiedades/-15077...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Jesus,j.jc2001@hotmail.com,525548828047,<NA>,ALTALTIUM REAL ESTATES VENTAS 1,Contactó por Whatsapp,2026-08-21 11:26:00,150778622,JN79,Edo. de México,Atizapán de Zaragoza,Condado de Sayavedra,Casa,Venta,1400000,CASA EXCLUSIVA EN VENTA EN CONDADO DE SAYAVEDR...,https://www.inmuebles24.com/propiedades/-15077...
137,Roger,roger.castillo@sweq.mx,525537331753,525537331753,ALTALTIUM REAL ESTATES VENTAS 1,Vió teléfono,2026-08-21 11:05:00,150794290,DV52,Edo. de México,Atizapán de Zaragoza,Rincón de la Montaña,Departamento,Venta,1569100,Departamento en venta en Rincón de la Montaña,https://www.inmuebles24.com/propiedades/-15079...
138,Jorge Calcaneo Vidal,calcaneovidaljorge@gmail.com,529994484743,529994484743,ALTALTIUM REAL ESTATES VENTAS 1,¡Hola! Quiero recibir información de sus inmue...,2026-08-21 03:30:00,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
139,Daniela Parra,daniparra.oficial@gmail.com,5633433616,<NA>,ALTALTIUM REAL ESTATES VENTAS 1,Contactó por Whatsapp,2026-08-21 02:35:00,150807995,AF78,Ciudad de México,Miguel Hidalgo,Bosque de las Lomas,Casa,Venta,5550000,"CASA BOSQUE DE LOS CIRUELOS, FRACC BOSQUE DE L...",https://www.inmuebles24.com/propiedades/-15080...
140,veronica,verodiaz27diaz@gmail.com,525518848018,525518848018,ALTALTIUM REAL ESTATES VENTAS 1,¡Hola! Quiero que se comuniquen conmigo por es...,2026-08-21 02:10:00,150792676,DV52,Ciudad de México,Venustiano Carranza,Jardín Balbuena,Departamento,Venta,1960200,Departamento en venta Jardín Balbuena,https://www.inmuebles24.com/propiedades/-15079...

In [5]:
import pandas as pd
import yaml
import psycopg2
from psycopg2.extras import execute_values


def insert_table(
    df: pd.DataFrame,
    yaml_path: str,
    connection
):
    with open(yaml_path, "r", encoding="utf-8") as file:
        config = yaml.safe_load(file)

    table_name = config["table"]

    columns = [
        column
        for column in config["columns"]
        if column["keep"]
    ]

    column_names = [column["name"] for column in columns]

    # Crear tabla si no existe
    definitions = ", ".join(
        f'"{column["name"]}" {column["sql_type"]}'
        for column in columns
    )

    create_query = f"""
        CREATE TABLE IF NOT EXISTS "{table_name}" (
            {definitions}
        );
    """

    cursor = connection.cursor()
    cursor.execute(create_query)

    # Preparar INSERT
    names = ", ".join(
        f'"{name}"'
        for name in column_names
    )

    insert_query = f"""
        INSERT INTO "{table_name}" ({names})
        VALUES %s;
    """

    # Convertir valores faltantes de pandas a None
    data = (
        df[column_names]
        .astype(object)
        .where(pd.notna(df[column_names]), None)
        .itertuples(index=False, name=None)
    )

    execute_values(
        cursor,
        insert_query,
        data
    )

    connection.commit()
    cursor.close()

In [ ]:
from src.db.connect import get_connection
conn = get_connection()
insert_table(
    test,
    "schemas/leads.yaml",
    connection
)

connection.close()