In [1]:
import pandas as pd
import set_paths
from config.paths import SCHEMAS, DATA, CRM, CITAS, INTERESADOS, ESTAD_PORTALES
from src.clean_tables import load_table
from src.utils import get_files
import yaml

In [2]:
table_path = get_files(CRM)[0]
test = load_table(path = CRM/table_path,
           yaml_path = SCHEMAS/"leads_table.YAML",
           date_format= "%d/%m/%Y %H:%M",
           day_first=True)
test["fecha_registro"]

0      2026-06-19 10:57:00
1      2026-06-19 10:56:00
2      2026-06-19 10:54:00
3      2026-06-19 10:53:00
4      2026-06-19 10:50:00
               ...
4847   2026-08-28 10:10:00
4848   2026-08-28 10:10:00
4849   2026-08-28 09:15:00
4850   2026-08-28 08:52:00
4851   2026-08-28 08:49:00
Name: fecha_registro, Length: 4852, dtype: datetime64[ns]

In [3]:
citas_test_path = get_files(CITAS)[0]
citas_test = load_table(path=CITAS / citas_test_path,
                        yaml_path= SCHEMAS/"citas_table.YAML")
citas_test

,id_lead,fecha_solicitud,fecha_cita,cliente,asesor,gerente,asistencia,n_cita,producto,tipo_cita,captacion,registrado_crm,ventas
0,10077,2026-09-04,2026-09-04,Luis Perez,Vanessa Herrera,Diego Becies,atendida,1,Residencial,inmueble,Cartera,True,0
1,9320,2026-08-31,2026-09-05,Adriana de los Santos,Manuel Alvarez,Victor Garcia,atendida,1,outlet,Presencial,Marketing,True,0
2,9689,2026-08-29,2026-09-05,Juan Brito,Alejandro Artola,Jaime Morales,cancelada,1,outlet,Presencial,Inmuebles24,True,0
3,9995,2026-09-05,2026-09-05,Concepcion N,Valentina Salgado,Leonardo Furlong,atendida,1,Residencial,inmueble,Inmuebles24,True,0
4,10114,2026-09-04,2026-09-05,Rey,Valentina Salgado,Leonardo Furlong,cancelada,1,Residencial,inmueble,Redes Sociales,True,0
5,6547,2026-09-04,2026-07-07,Magdalena Hernandez,Daniel Guerra,Leonardo Furlong,cancelada,1,outlet,Presencial,Marketing,True,0
6,9967,2026-09-02,2026-09-07,Juan,Diana Vivanco,Omar Moreno,cancelada,1,outlet,Presencial,Cartera,True,0
7,9320,2026-09-05,2026-09-07,Adriana de los Santos,Manuel Alvarez,Victor Garcia,atendida,2,outlet,videollamada,Marketing,True,0
8,9888,2026-09-04,2026-09-07,Elvira Plaza,Daniel Guerra,Leonardo Furlong,atendida,1,Residencial,inmueble,Redes Sociales,True,0
9,10310,2026-09-08,2026-09-08,Jesus Sanchez,Omar Moreno,Jaime Morales,atendida,1,Recover,Presencial,cartera,True,0
10,10283,2026-09-07,2026-09-08,Honorato N,Claudia del Toro,Leonardo Furlong,reagendada,1,Residencial,inmueble,Inmuebles24,True,0
11,10152,2026-09-08,2026-09-09,Veronica N,Diana Vivanco,Janeth Jimenez,reagendada,1,outlet,Presencial,Inmuebles24,True,0
12,6547,2026-09-09,2026-09-09,Magdalena Hernandez,Daniel Guerra,Leonardo Furlong,atendida,1,outlet,inmueble,Marketing,True,0
13,9891,2026-09-01,2026-09-09,Josafat N,Diana Vivanco,Janeth Jimenez,cancelada,1,outlet,Presencial,Inmuebles24,True,0
14,8064,2026-09-08,2026-09-09,Javier Antonio Goldaracena,Arturo Gonzalez,Victor Garcia,atendida,5,Soluciones Legales,Presencial,Cartera,True,1
15,10377,2026-09-09,2026-09-09,Arturo Mejia,Janeth Jimenez,Jaime Morales,atendida,1,outlet,Presencial,Inmuebles24,True,0
16,10152,2026-09-08,2026-09-09,Veronica N,Diana Vivanco,Janeth Jimenez,cancelada,2,outlet,Presencial,Inmuebles24,True,0
17,8330,2026-08-31,2026-09-10,Angel Rios,Patricia Mijares,Victor Garcia,reagendada,3,Micro,videollamada,Redes Sociales,True,0
18,8330,2026-09-07,2026-09-10,Angel Rios,Patricia Mijares,Victor Garcia,atendida,3,Micro,videollamada,Redes Sociales,True,0
19,9962,2026-09-08,2026-09-10,Javier,Dubia Ilescas,Diego Becies,atendida,1,outlet,videollamada,Inmuebles24,True,0

In [ ]:
inter_test_path = get_files(INTERESADOS)[0]
inter_test = load_table(path=INTERESADOS / inter_test_path,
                        yaml_path= SCHEMAS/"interesados_table.YAML",
                        date_format="mixed",
                        day_first= True)
duplicados = inter_test[
    inter_test.duplicated(
        subset=["email", "fecha", "id_portal", "id_aviso"],#LLAVE CANDIDATA
        keep=False
    )
].sort_values(["email", "fecha"])

duplicados#[duplicados["id_aviso"] == 0]

Empty DataFrame
Columns: [nombre_apellido, email, telefono, telefono_2, id_portal, fecha, id_aviso, codigo, provincia, ciudad, barrio, tipo_propiedad, tipo_operacion, precio]
Index: []

In [5]:
stats_test_path = get_files(INTERESADOS)[1]
stats_test = load_table(path=INTERESADOS / inter_test_path,
                        yaml_path= SCHEMAS/"interesados_table.YAML")
stats_test

,nombre_apellido,email,telefono,telefono_2,id_portal,fecha,id_aviso,codigo,provincia,ciudad,barrio,tipo_propiedad,tipo_operacion,precio
0,Raul,raulgoh7@gmail.com,5530808634,<NA>,1,NaT,150965844,BH81,Ciudad de México,Benito Juárez,Actipan,Departamento,Venta,2100000
1,DIEGO,d.becies@altaltiumrealestates.com,525621881886,5621881886,1,NaT,151043903,DB80,Ciudad de México,Alvaro Obregón,Jardines del Pedregal,Casa,Venta,9850000
2,Norma Rebeca Fernández cantero Norma Fernández,norma.fernandez51@yahoo.com.mx,525632716621,<NA>,1,NaT,150807882,JN79,Ciudad de México,Venustiano Carranza,Jardín Balbuena,Casa,Venta,2700000
3,Diana,darzt@jowat.com,525647075275,525647075275,1,NaT,150910972,DB80,Ciudad de México,Benito Juárez,Insurgentes Mixcoac,Departamento,Venta,1900000
4,Karen,gytabogados@hotmail.com,5538965293,5538965293,1,NaT,150981070,JA48,Ciudad de México,Venustiano Carranza,Moctezuma,Departamento,Venta,1192542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4362,Elizabeth,elyz411cg@gmail.com,525584764514,525584764514,4,NaT,149831218,DIr1,Edo. de México,Cuautitlán Izcalli,San Francisco Tepojaco,Casa,Venta,1118480
4363,JESSICA,hanna.jv87@gmail.com,525526651677,<NA>,4,NaT,148835238,EL07,Ciudad de México,Cuauhtémoc,Doctores,Departamento,Venta,785000
4364,Karla Gabriela,kgabriela.jacintoc@gmail.com,525529522691,525529522691,4,NaT,149761528,EL07,Ciudad de México,Benito Juárez,Álamos,Departamento,Venta,2092887
4365,Alberto y,aguilaralberto6451@gmail.com,525564966055,525564966055,4,NaT,149306715,EL07,Ciudad de México,Cuauhtémoc,Doctores,Departamento,Venta,785000
4366,Alma Dejesus Ruiz,dejesusruizalma@gmail.com,525561576303,525561576303,4,NaT,149498489,EL07,Edo. de México,Atizapán de Zaragoza,Villas de la Hacienda,Casa,Venta,510000